### ISSUE TITLE
是不是站点文件bin没有改，发现馒头失效

### ISSUE THREAD

**Issue by jackloves111** [0xforee/nas-tools#1]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.4.1

### 问题类型

主程序运行问题

### 问题描述

你是不是站点文件bin没有改，发现馒头失效

### 发生问题时系统日志和配置文件

```bash
你是不是站点文件bin没有改，发现馒头失效
```

**Comment by jackloves111** [comment]
hsuyelin版 的站点配置，馒头是缺少一个字典的

**Comment by 0xforee** [comment]
直接从之前我的版本拷过来的，是全的
你有具体的日志报错没？贴个看看
