### ISSUE TITLE
[功能改进]: 关于修改做种文件名字的功能

### ISSUE THREAD

**Issue by 188334911** [0xforee/nas-tools#12]
### 当前程序版本

3.49

### 功能改进

自行测试了一下，qb内将正在做种的文件夹和文件名修改之后也能正常做种，能不能出一个插件，下载后根据刮削内容，在QB内自动修改文件夹、文件名，这样既能 正常做种，也可以顺利入库，包括之后的观看、删除都是在改名后的源文件夹上操作，简化了很多步骤

**Comment by 0xforee** [comment]
已沟通，可以通过硬链接+自动删种任务解决哈
