### ISSUE TITLE
[错误报告]: 

### ISSUE THREAD

**Issue by xmlijian** [0xforee/nas-tools#14]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.1

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/0xforee/nas-tools/assets/18203573/4f57cb5e-1b2d-419e-a010-666ecc6db51d)
刷流的时候 免费不能选。 
在不选择站点的时候免费是可以选择的。当选择完站点之后就会自动跳到促销 全部的分类且无法选择免费，只有一个全部可选。
![image](https://github.com/0xforee/nas-tools/assets/18203573/40b2f776-7f6b-466f-9130-7b44d8cda62d)

**Comment by 0xforee** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 3.5.1
> 
> ### 问题类型
> 主程序运行问题
> 
> ### 问题描述
> ![image](https://private-user-images.githubusercontent.com/18203573/346486150-4f57cb5e-1b2d-419e-a010-666ecc6db51d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTQwODgsIm5iZiI6MTcyMDg1Mzc4OCwicGF0aCI6Ii8xODIwMzU3My8zNDY0ODYxNTAtNGY1N2NiNWUtMWIyZC00MTllLWEwMTAtNjY2ZWNjNmRiNTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA2NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzQ1MmRmNDY3MDkwMjIxNDI2Y2Y4YjRhYTllOWM2NTc0YmJhNWE0OTExOWZkZDJlNmU4Mzg5NjdiZDZlMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C8V_6EV5prTrjr0ageIiCkiQyTLvvPOJTo48M2hu5RE) 刷流的时候 免费不能选。 在不选择站点的时候免费是可以选择的。当选择完站点之后就会自动跳到促销 全部的分类且无法选择免费，只有一个全部可选。 ![image](https://private-user-images.githubusercontent.com/18203573/346486738-40b2f776-7f6b-466f-9130-7b44d8cda62d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTQwODgsIm5iZiI6MTcyMDg1Mzc4OCwicGF0aCI6Ii8xODIwMzU3My8zNDY0ODY3MzgtNDBiMmY3NzYtN2Y2Yi00NjZmLTkxMzAtN2I0NGQ4Y2RhNjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA2NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGYyM2JmNGVhNWRmYTJiNzUyZWVmZTQ0NWY5YzQ0Nzk5MzgzM2ZkNjZhYmVjYTNkZmEzMDA3ZGU5M2UzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XSZYt3ZzUsUjQU-C_SzoxvntqpvLT7Gyp1huFdc9uZk)
> 
> ### 发生问题时系统日志和配置文件
> _No response_

右上角更新，拉下最新代码试试
