### ISSUE TITLE
无法添加馒头站点 - 未配置站点Cookie

### ISSUE THREAD

**Issue by Kings-Github** [0xforee/nas-tools#15]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.1

### 问题类型

主程序运行问题

### 问题描述

我是docker部署的此项目，从原项目（hsuyelin/nas-tools）直接升级到本项目的3.5.1版本，是删除了原项目docker镜像，重新部署的，原来的配置文件是沿用的。添加馒头站点提示我要cookie，我不知道如何在新版本的馒头站点获取cookie，不是直接添加API代码（令牌）就可以成功访问了吗？
错误提示：未配置站点Cookie（不清楚如何获取emmmm）
此页面看到的项目：https://github.com/hsuyelin/nas-tools/issues/737

**Comment by Kings-Github** [comment]
原项目（hsuyelin/nas-tools）是3.4.0升级的本项目3.5.1版本，Docker部署方式

**Comment by Kings-Github** [comment]
我又测试了全新安装3.5.1，docker安装方式，发现添加馒头站点时，cookie栏目随便写一个网站的就没有提示报错了，就不提示：未配置站点Cookie，直接就可以连通了，但是索引器里面依然看不到添加的馒头站点，不知道为什么？

**Comment by 0xforee** [comment]
右上角更新，拉下最新代码，参考：https://github.com/0xforee/nas-tools/wiki/%E5%A6%82%E4%BD%95%E6%8A%93%E5%8F%96%E6%97%A5%E5%BF%97%EF%BC%9F
这里 3.5.2 版本的抓取下最新日志看看（注意隐藏日志中个人信息

**Comment by Ekkone** [comment]
> 我又测试了全新安装3.5.1，docker安装方式，发现添加馒头站点时，cookie栏目随便写一个网站的就没有提示报错了，就不提示：未配置站点Cookie，直接就可以连通了，但是索引器里面依然看不到添加的馒头站点，不知道为什么？

请问您这边解决了没？我遇到了相同的问题

**Comment by Ekkone** [comment]
我随便填了cookie后索引器是正常的，使用没问题
