### ISSUE TITLE
馒头跟1PT不能模拟登录签到

### ISSUE THREAD

**Issue by lan771** [0xforee/nas-tools#16]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.1

### 问题类型

插件问题

### 问题描述

馒头跟1PT都能连通性测试通过。确认cookie最新
使用插件签到提示错误：
1.1ptba | 模拟登录失败，Cookie已失效！
2.馒头 签到失败：'NoneType' object has no attribute 'get'

**Comment by 0xforee** [comment]
馒头签到可以参考这里：https://github.com/0xforee/nas-tools/wiki/%E9%A6%92%E5%A4%B4%E7%AD%BE%E5%88%B0%E9%A1%BB%E7%9F%A5
