### ISSUE TITLE
MT无法签到，Cookie无法更新

### ISSUE THREAD

**Issue by jy00804902** [0xforee/nas-tools#17]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.1

### 问题类型

主程序运行问题

### 问题描述

MT无法签到，提示为：触发邮箱登录，无法签到，请在站点管理处更新站点信息。
尝试在站点维护页面更新Cookie，点击开始更新后，跳出输入邮箱提示，60秒内输入完毕，但没有更新成功，弹出一个橙色提示框，框内空白。
查看实时日志，显示：
16:52:52 | Sites | 开始更新 M-Team Cookie和User-Agent ...
16:53:00 | System | Challenge not detected!
16:53:32 | Sites | 接收到 email：xxxxxxx@gmail.com
![Snip20240713_1](https://github.com/user-attachments/assets/d02fda3c-0fa2-48d5-8abe-ff6d1dd6aab3)

**Comment by 0xforee** [comment]
再重新点击下开始更新，如果提示 cookie 未失效就可以了

**Comment by jy00804902** [comment]
> 重新重新点击下开始更新，如果提示cookie未失效就可以了

不行啊，再点开始更新又会提示60s内输入邮箱，输入完成后又跳出空白的橙色提示框，无限循环
