### ISSUE TITLE
mt无法获取到cookie，log日志截图如下

### ISSUE THREAD

**Issue by ppch4** [0xforee/nas-tools#18]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.2

### 问题类型

主程序运行问题

### 问题描述

仍然是mt无法获取cookie
![image](https://github.com/user-attachments/assets/197a0da8-daf5-4ba7-97c3-a8ddcb5cf2a3)

**Comment by 0xforee** [comment]
cookies有了，看日志 已登陆且cookie未失效
