### ISSUE TITLE
[错误报告]: MT站点不行，无法登录

### ISSUE THREAD

**Issue by cikichen** [0xforee/nas-tools#19]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.5.2

### 问题类型

主程序运行问题

### 问题描述

登录后提示已经已经登录过且Cookie未失效，但是刷流，站点资源都用不了

### 发生问题时系统日志和配置文件

![QQ_1722597656780](https://github.com/user-attachments/assets/60af8230-646d-4368-8e0b-c98fbead4c3f)

**Comment by 0xforee** [comment]
cookies仅用来签到 刷流和其他的需要配置令牌

**Comment by cikichen** [comment]
> cookies仅用来签到 刷流和其他的需要配置令牌

令牌也配置了
