### ISSUE TITLE
[功能改进]: 刷流任务的下载目录这里不会用，一直提示目录没有挂载。

### ISSUE THREAD

**Issue by Zhaihaozhou** [0xforee/nas-tools#2]
### 当前程序版本

3.4.2

### 功能改进

下载器qb里面已经按照我的影视分类设置了多个下载目录，有点混乱，对于我这种小白来说，感觉还是之前的直接在刷流任务中指定就好，这样不涉及nt映射目录，只在qb映射，主要部分下载规则那里也看不懂，用不到哈哈。感谢大佬

**Comment by 0xforee** [comment]
1.下载器设置可以针对同一个下载器指定多个下载目录，所以映射本身不存在问题
2.刷流任务如果直接指定下载目录，NT 感知不到磁盘空间大小，会导致磁盘刷爆的可能性
3.部分下载规则（拆包）：简单来说就是对指定区间大小的种子计算要保留的比例，比如0-100GB的种子，保留比例0.5（50%），下载器就会挑种子文件中合适的文件达到这个大小，达到拆包的目的。（我又更新了一版说明，可以再看看）

**Comment by 0xforee** [comment]
使用说明：
——————
部分下载能力：也叫拆包。规则由三部分构成，来达到最灵活的配置。
1. 种子大小范围：这个规则用来将种子按照这个配置规则映射到合适的大小区间。
2. 下载比例：根据 1 的区间，对应到合适的下载比例。
3. 计算后限定范围：左边限定值 <=   种子大小*下载比例 <= 右边限定值

举例来说：
1. 种子大小范围：0, 100, 200。
2. 下载比例，1, 0.5, 0.1。
3.计算后限定（GB），30-50

有一个种子大小为 130GB，那么会落在种子大小范围 100-200 的区间。那么对应的下载比例为 0.5，也就是会下载 130*0.5 = 65GB 的数据
但种子最终限定是 30-50GB，所以最后下载的大小不超过 50GB，也就是 50GB
所以，会遍历种子中的每个文件，挑选合适的文件，使得种子总大小<=50GB，达到拆包的目的

**Comment by Zhaihaozhou** [comment]
感谢大佬回复，已经弄好了，我没有设置下载器，跟qb一样的目录映射进nt就好了

**Comment by Zhaihaozhou** [comment]
> 1.下载器设置可以针对同一个下载器指定多个下载目录，所以映射本身不存在问题 2.刷流任务如果直接指定下载目录，NT 感知不到磁盘空间大小，会导致磁盘刷爆的可能性 3.部分下载规则（拆包）：简单来说就是对指定区间大小的种子计算要保留的比例，比如0-100GB的种子，保留比例0.5（50%），下载器就会挑种子文件中合适的文件达到这个大小，达到拆包的目的。（我又更新了一版说明，可以再看看）

感谢大佬回复，已经弄好了，我没有设置下载器，跟qb一样的目录映射进nt就好了
