### ISSUE TITLE
[错误报告]: 插件页面打不开

### ISSUE THREAD

**Issue by aat002** [0xforee/nas-tools#29]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/0xforee/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/0xforee/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.5.5 00689cd

### 问题类型

主程序运行问题

### 问题描述

最新版本，插件页面打不开，顶部进度条在走动
![屏幕截图 2024-11-07 213927](https://github.com/user-attachments/assets/92d38016-1671-4481-a213-48df698e2bfa)

**Comment by 0xforee** [comment]
在 #20 已修复
