### ISSUE TITLE
[错误报告]: 应用内日志不刷新或正在加载中

### ISSUE THREAD

**Issue by anan6688** [0xforee/nas-tools#3]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.3

### 问题类型

主程序运行问题

### 问题描述

应用内实时日志不刷新，如果打开第二个页面，再看实时日志，会一直正在加载中，

**Comment by anan6688** [comment]
![1713143283242](https://github.com/0xforee/nas-tools/assets/77087397/71cc001d-9083-4621-b523-73e21f52c9cc)

**Comment by anan6688** [comment]
另外docker里看容器日志会有一些报错，如图，请问是缺少什么依赖么？
![1713143355668](https://github.com/0xforee/nas-tools/assets/77087397/4e46c091-4372-47f0-a816-3e77578eb334)

**Comment by anan6688** [comment]
容器是全新拉取的，尝试过再次拉取，问题依旧

**Comment by anan6688** [comment]
更新下问题，如果打开一直等待，20-40分钟有可能加载出来日志，但是如上面描述，不会更新日志，也许在实时日志界面停留长时间有可能更新出来。

**Comment by 0xforee** [comment]
你的日志大小有多少？可以看下docker 日志里右下角 有多少行数

**Comment by anan6688** [comment]
目前5920行，因为有刷流，所以在慢慢增加

**Comment by 0xforee** [comment]
> 目前5920行，因为有刷流，所以在慢慢增加

你加下tg群，我找你拿下日志

**Comment by 0xforee** [comment]
> 目前5920行，因为有刷流，所以在慢慢增加

可以加下 tg，然后群里反馈下，我本地还是无法复现这个问题

**Comment by anan6688** [comment]
更新新版没问题啦
