### ISSUE TITLE
[错误报告]: 多个站点添加任务失败

### ISSUE THREAD

**Issue by Zhaihaozhou** [0xforee/nas-tools#4]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.4.3

### 问题类型

主程序运行问题

### 问题描述

昨晚九点以后岛、红叶、家园等多个站点反馈种子数据有误，添加任务失败，观众反馈种子添加失败403，中午都还正常，看了下好像就是大佬昨晚更新的时间，是不是有哪里出错了

**Comment by 0xforee** [comment]
昨晚更新只mteam相关内容，你试试更新下站点 cookie，看问题还在不

**Comment by Zhaihaozhou** [comment]
![Quicker_20240416_132842](https://github.com/0xforee/nas-tools/assets/116950604/ed828100-be94-465c-90ee-af3edea30807)
cookie也更新了 没用，还有上面关于rss的错误 看不懂啥意思

**Comment by Zhaihaozhou** [comment]
> 昨晚更新只mteam相关内容，你试试更新下站点 cookie，看问题还在不

![Quicker_20240416_132842](https://github.com/0xforee/nas-tools/assets/116950604/2e7e5955-0c0d-465b-8786-aa3ecea9dcc6)
cookie也更新了 没用，还有上面关于rss的错误 看不懂啥意思

**Comment by Zhaihaozhou** [comment]
> 昨晚更新只mteam相关内容，你试试更新下站点 cookie，看问题还在不

大佬已经解决了，应该是我本地的容器有问题了，我把删了重新拉取镜像创建容器就好了= =
