### ISSUE TITLE
[功能改进]: 求更新AGSV末日索引 ~~

### ISSUE THREAD

**Issue by tasty007** [0xforee/nas-tools#5]
### 当前程序版本

v3.4.3

### 功能改进

求更新AGSV末日索引 ~~
建议内置添加一个第三方索引插件, 支持自定义索引.
可参考 https://github.com/Mattoids/nas-tools-plugin

**Comment by 0xforee** [comment]
> ### 当前程序版本
> v3.4.3
> 
> ### 功能改进
> 求更新AGSV末日索引 ~~ 建议内置添加一个第三方索引插件, 支持自定义索引. 可参考 https://github.com/Mattoids/nas-tools-plugin
> 
> ### 参考资料
> _No response_

抱歉，没有这个站点账号，要更新索引的话可能需要你提供一些信息，可以加 tg 给一下~

**Comment by 0xforee** [comment]
已适配站点
