### ISSUE TITLE
[功能改进]: 希望刷流任务可以有禁止拆包的选项。

### ISSUE THREAD

**Issue by buzidjy** [0xforee/nas-tools#6]
### 当前程序版本

 v3.4.5 32e8a74

### 功能改进

发现大量种子就选择了几百K的nfo文件下，应该是在凑保种体积。能不能选择禁止拆包，如果下载这个完整的种子会超过保种体积那就跳过不下载好了。我的拆包规则是留空，默认不是禁止拆包吗？
![2](https://github.com/0xforee/nas-tools/assets/122658705/5f8f00c9-f389-4dc2-a4d0-b538e28164fb)
![1](https://github.com/0xforee/nas-tools/assets/122658705/616fa21f-e4f0-44a5-889d-93e6bcbded99)

**Comment by 0xforee** [comment]
部分下载规则置空的情况下，不会再开启拆包功能了。NT->右上角->更新 拉取最新版试试

**Comment by buzidjy** [comment]
> 部分下载规则置空的情况下，不会再开启拆包功能了。NT->右上角->更新 拉取最新版试试

好的谢谢
