### ISSUE TITLE
[错误报告]: 刷流RSS获取不到信息

### ISSUE THREAD

**Issue by anan6688** [0xforee/nas-tools#7]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/hsuyelin/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/hsuyelin/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v3.4.5 4268d7f

### 问题类型

主程序运行问题

### 问题描述

刷流时候RSS获取不到信息，经过TG群沟通后发现，在刷流任务中设置了同时下载任务数后，导致刷流任务无法获取到RSS信息。

**Comment by 0xforee** [comment]
当前任务下载数和站点任务数要一起设置，不然会报错。
我在新版中增加了这两个参数的校验，可以试试看
